"""
Custom Lab LIMS Web — FastAPI + Jinja2 entry point.
First-run Lab Setup wizard → login → modular lab workspace.
No Streamlit.
"""
from __future__ import annotations

import csv
import io
import json
import secrets
from datetime import date
from pathlib import Path
from typing import Any, Optional

from fastapi import Depends, FastAPI, File, Form, Request, UploadFile
from fastapi.responses import FileResponse, HTMLResponse, RedirectResponse, Response, StreamingResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from starlette.middleware.sessions import SessionMiddleware

from auth import hash_password, role_can, verify_password
from bio_utils import local_search, parse_fasta
from db import (
    ASSAY_TYPE_SUGGESTIONS,
    DEFAULT_MODULES,
    HUSBANDRY_LABEL_OPTIONS,
    LAB_TYPE_OPTIONS,
    get_db,
    reset_db_cache,
)
from labs import (
    active_lab_code,
    create_empty_lab,
    list_labs,
    register_lab,
    switch_active_lab,
    validate_lab_code,
)
from services.external import (
    cif_to_pdb,
    fetch_rcsb_entry_meta,
    fetch_rcsb_structure,
    pubchem_lookup,
    save_bytes,
    uniprot_fetch,
    uniprot_search,
)

ROOT = Path(__file__).resolve().parent
UPLOAD_DIR = ROOT / "uploads"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
STRUCTURES_DIR = UPLOAD_DIR / "structures"
STRUCTURES_DIR.mkdir(parents=True, exist_ok=True)

SECRET_KEY = secrets.token_hex(32)
# Persist a stable secret across reloads when possible
_secret_file = ROOT / "data" / ".session_secret"
try:
    if _secret_file.exists():
        SECRET_KEY = _secret_file.read_text().strip() or SECRET_KEY
    else:
        _secret_file.parent.mkdir(parents=True, exist_ok=True)
        _secret_file.write_text(SECRET_KEY)
except Exception:
    pass

app = FastAPI(title="Custom Lab LIMS", docs_url=None, redoc_url=None)
app.add_middleware(SessionMiddleware, secret_key=SECRET_KEY, max_age=60 * 60 * 12)
app.mount("/static", StaticFiles(directory=str(ROOT / "static")), name="static")
templates = Jinja2Templates(directory=str(ROOT / "templates"))

def render(request: Request, name: str, context: dict, status_code: int = 200):
    """Starlette 1.6+ TemplateResponse(request, name, context)."""
    return templates.TemplateResponse(request, name, context, status_code=status_code)


class _DBProxy:
    """Always resolve the active per-lab Database (survives lab switches)."""

    def __getattr__(self, name: str):
        return getattr(get_db(), name)


db = _DBProxy()


def safe_upload_path(directory: Path, filename: str) -> Path:
    """Resolve a filename under directory; reject path traversal."""
    directory = directory.resolve()
    raw = Path(filename or "").name
    if not raw or raw in (".", ".."):
        raise ValueError("Invalid filename")
    # Strip weird characters that confuse filesystems / Content-Disposition
    safe = "".join(c if c.isalnum() or c in "._-+" else "_" for c in raw)
    if not safe or safe.startswith("."):
        raise ValueError("Invalid filename")
    dest = (directory / safe).resolve()
    if not str(dest).startswith(str(directory) + "/") and dest != directory:
        # Windows-friendly: also allow same root via relative_to
        try:
            dest.relative_to(directory)
        except ValueError as e:
            raise ValueError("Path escapes upload directory") from e
    return dest


def safe_structure_read(rel_or_abs: str) -> Path:
    """Only allow reading structure files under uploads/structures."""
    path = Path(rel_or_abs)
    if not path.is_absolute():
        path = (ROOT / path).resolve()
    else:
        path = path.resolve()
    base = STRUCTURES_DIR.resolve()
    try:
        path.relative_to(base)
    except ValueError as e:
        raise ValueError("Structure path outside uploads/structures") from e
    return path

R_TEMPLATE = '''# Auto-generated by Custom Lab LIMS — ggplot2 assay chart
# Requires: tidyverse (ggplot2, readr)
library(ggplot2)
library(readr)

args <- commandArgs(trailingOnly = TRUE)
csv_path <- if (length(args) >= 1) args[[1]] else "assays_export.csv"
out_path <- if (length(args) >= 2) args[[2]] else "assay_chart.png"

df <- read_csv(csv_path, show_col_types = FALSE)
if (!"survival_percent" %in% names(df)) stop("survival_percent column missing")

p <- ggplot(df, aes(x = assay_date, y = survival_percent, color = assay_type)) +
  geom_point(size = 3, alpha = 0.85) +
  geom_line(aes(group = assay_type), alpha = 0.4) +
  theme_minimal(base_size = 12) +
  labs(title = "Assay metrics over time", x = "Date", y = "Metric value", color = "Type")

ggsave(out_path, p, width = 8, height = 5, dpi = 150)
message("Wrote ", out_path)
'''


def flash(request: Request, message: str, category: str = "info") -> None:
    flashes = request.session.get("_flashes") or []
    flashes.append({"message": message, "category": category})
    request.session["_flashes"] = flashes


def pop_flashes(request: Request) -> list[dict]:
    flashes = request.session.pop("_flashes", None) or []
    return flashes


def current_user(request: Request) -> Optional[dict]:
    user = request.session.get("user")
    if isinstance(user, dict) and user.get("username"):
        return user
    return None


def require_user(request: Request) -> Optional[RedirectResponse]:
    if not db.has_lab_config():
        return RedirectResponse("/setup", status_code=303)
    if not current_user(request):
        return RedirectResponse("/login", status_code=303)
    return None


def build_nav(config: dict) -> list[dict]:
    mods = config.get("modules") or {}
    h_label = config.get("husbandry_label") or "Organisms"
    items = [
        {"key": "home", "label": "Home", "href": "/", "module": None},
        {"key": "samples", "label": "Samples", "href": "/samples", "module": "samples"},
        {"key": "compounds", "label": "Compounds", "href": "/compounds", "module": "compounds"},
        {"key": "experiments", "label": "Experiments", "href": "/experiments", "module": "experiments"},
        {"key": "husbandry", "label": h_label, "href": "/husbandry", "module": "husbandry"},
        {"key": "protocols", "label": "Protocols", "href": "/protocols", "module": "protocols"},
        {"key": "proteins", "label": "Proteins", "href": "/proteins", "module": "proteins"},
        {"key": "bioinformatics", "label": "Bioinformatics", "href": "/bioinformatics", "module": "bioinformatics"},
        {"key": "analytics", "label": "Analytics", "href": "/analytics", "module": "analytics"},
        {"key": "integrations", "label": "Integrations", "href": "/integrations", "module": None},
        {"key": "guide", "label": "Guide", "href": "/guide", "module": None},
        {"key": "users", "label": "Users", "href": "/users", "module": "users"},
        {"key": "audit", "label": "Audit", "href": "/audit", "module": "audit"},
        {"key": "settings", "label": "Settings", "href": "/settings", "module": None},
    ]
    out = []
    for it in items:
        mod = it["module"]
        if mod is None or mods.get(mod, True):
            out.append(it)
    return out


def module_enabled(config: dict, key: str) -> bool:
    return bool((config.get("modules") or {}).get(key, True))


def ctx(request: Request, active: str = "", **extra: Any) -> dict:
    config = db.get_lab_config()
    user = current_user(request)
    # Session lab binding — force re-login if active lab changed underfoot
    if user:
        sess_lab = request.session.get("lab_code")
        cur = active_lab_code()
        if cur and sess_lab and sess_lab != cur:
            request.session.clear()
            user = None
    base = {
        "request": request,
        "config": config,
        "user": user,
        "nav": build_nav(config) if config and user else [],
        "active": active,
        "flashes": pop_flashes(request),
        "can_write": role_can(user["role"], "write") if user else False,
        "can_admin": role_can(user["role"], "admin") if user else False,
        "active_lab_code": active_lab_code(),
        "labs_registry": list_labs(),
    }
    base.update(extra)
    return base


def redirect(url: str) -> RedirectResponse:
    return RedirectResponse(url, status_code=303)


# ── Setup / Auth ────────────────────────────────────────────────
@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    if not db.has_lab_config():
        return redirect("/setup")
    if not current_user(request):
        return redirect("/login")
    config = db.get_lab_config()
    return render(request, 
        "dashboard.html",
        ctx(
            request,
            active="home",
            counts=db.dashboard_counts(),
            audit=db.recent_audit(8),
        ),
    )


@app.get("/setup", response_class=HTMLResponse)
async def setup_get(request: Request):
    if db.has_lab_config():
        return redirect("/login")
    return render(request, 
        "setup.html",
        {
            "request": request,
            "config": None,
            "user": None,
            "flashes": pop_flashes(request),
            "lab_types": LAB_TYPE_OPTIONS,
            "husbandry_labels": HUSBANDRY_LABEL_OPTIONS,
            "module_keys": list(DEFAULT_MODULES.keys()),
        },
    )


@app.post("/setup")
async def setup_post(
    request: Request,
    lab_name: str = Form(...),
    lab_code: str = Form(...),
    lab_type: str = Form("General"),
    lab_type_other: str = Form(""),
    husbandry_label: str = Form("Organisms"),
    husbandry_custom: str = Form(""),
    primary_color: str = Form("#2563eb"),
    accent_color: str = Form("#0d9488"),
    timezone: str = Form("America/Los_Angeles"),
    logo_path: str = Form(""),
    admin_user: str = Form(...),
    admin_pw: str = Form(...),
    admin_pw2: str = Form(...),
):
    if db.has_lab_config():
        return redirect("/login")
    form = await request.form()
    selected = form.getlist("modules")
    mods = {k: (k in selected) for k in DEFAULT_MODULES}

    errors = []
    if not lab_name.strip():
        errors.append("Lab name is required.")
    if not lab_code.strip():
        errors.append("Lab code is required.")
    if not admin_user.strip():
        errors.append("Admin username is required.")
    if not admin_pw or len(admin_pw) < 6:
        errors.append("Admin password must be at least 6 characters.")
    if admin_pw != admin_pw2:
        errors.append("Passwords do not match.")
    if errors:
        for e in errors:
            flash(request, e, "error")
        return redirect("/setup")

    final_type = lab_type_other.strip() or lab_type
    final_h = husbandry_custom.strip() or husbandry_label
    try:
        code = validate_lab_code(lab_code)
    except ValueError as e:
        flash(request, str(e), "error")
        return redirect("/setup")

    db.save_lab_config(
        lab_name=lab_name.strip(),
        lab_code=code,
        primary_color=primary_color,
        accent_color=accent_color,
        timezone=timezone.strip() or "UTC",
        logo_path=logo_path.strip() or None,
        modules=mods,
        lab_type=final_type,
        husbandry_label=final_h,
    )
    if not db.get_user_by_username(admin_user.strip()):
        db.create_user(
            admin_user.strip(),
            hash_password(admin_pw),
            "admin",
            admin_user.strip(),
        )
    db.audit(
        "lab_setup",
        username=admin_user.strip(),
        role="admin",
        details=f"lab={lab_name.strip()} type={final_type}",
    )
    # Move/register into data/labs/<CODE>/lab.db
    register_lab(code, lab_name.strip(), make_active=True)
    reset_db_cache()
    flash(request, "Lab configured. Please sign in.", "success")
    return redirect("/login")


@app.get("/login", response_class=HTMLResponse)
async def login_get(request: Request):
    if not db.has_lab_config():
        return redirect("/setup")
    if current_user(request):
        return redirect("/")
    return render(request, "login.html", ctx(request))


@app.post("/login")
async def login_post(
    request: Request,
    username: str = Form(...),
    password: str = Form(...),
):
    if not db.has_lab_config():
        return redirect("/setup")
    row = db.get_user_by_username(username.strip())
    if row and verify_password(row["password_hash"], password):
        request.session["user"] = {
            "id": row["id"],
            "username": row["username"],
            "role": row["role"],
            "display_name": row.get("display_name") or row["username"],
        }
        request.session["lab_code"] = active_lab_code()
        db.audit("login", row["username"], row["role"], "success")
        return redirect("/")
    db.audit("login_failed", username.strip() or None, None, "bad credentials")
    flash(request, "Invalid username or password.", "error")
    return redirect("/login")


@app.get("/logout")
async def logout(request: Request):
    user = current_user(request)
    if user:
        db.audit("logout", user["username"], user["role"], "ok")
    request.session.clear()
    return redirect("/login")


# ── Samples ─────────────────────────────────────────────────────
@app.get("/samples", response_class=HTMLResponse)
async def samples_page(request: Request):
    if (r := require_user(request)):
        return r
    config = db.get_lab_config()
    if not module_enabled(config, "samples"):
        flash(request, "Samples module disabled.", "error")
        return redirect("/")
    return render(request, 
        "samples.html", ctx(request, active="samples", rows=db.list_samples())
    )


@app.post("/samples/add")
async def samples_add(
    request: Request,
    name: str = Form(...),
    sample_type: str = Form("general"),
    quantity: float = Form(0),
    unit: str = Form("units"),
    location: str = Form(""),
    status: str = Form("available"),
    notes: str = Form(""),
):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/samples")
    db.add_sample(
        name=name.strip(),
        sample_type=sample_type.strip() or "general",
        quantity=quantity,
        unit=unit.strip() or "units",
        location=location.strip() or None,
        status=status.strip() or "available",
        notes=notes.strip() or None,
        created_by=user["username"],
    )
    db.audit("sample_add", user["username"], user["role"], name.strip())
    flash(request, "Sample saved.", "success")
    return redirect("/samples")


@app.post("/samples/{sample_id}/delete")
async def samples_delete(request: Request, sample_id: int):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/samples")
    db.delete_sample(sample_id)
    db.audit("sample_delete", user["username"], user["role"], str(sample_id))
    flash(request, "Sample deleted.", "success")
    return redirect("/samples")


# ── Compounds ───────────────────────────────────────────────────
@app.get("/compounds", response_class=HTMLResponse)
async def compounds_page(request: Request):
    if (r := require_user(request)):
        return r
    draft = request.session.pop("compound_draft", None) or {}
    return render(request, 
        "compounds.html",
        ctx(
            request,
            active="compounds",
            rows=db.list_compounds(),
            pubchem_result=request.session.pop("pubchem_result", None),
            draft_name=draft.get("name", ""),
            draft_smiles=draft.get("smiles", ""),
            draft_mw=draft.get("mw", ""),
            draft_formula=draft.get("formula", ""),
        ),
    )


@app.post("/compounds/add")
async def compounds_add(
    request: Request,
    name: str = Form(...),
    status: str = Form("active"),
    mw: Optional[str] = Form(None),
    smiles: str = Form(""),
    notes: str = Form(""),
):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/compounds")
    mw_val = float(mw) if mw not in (None, "") else None
    try:
        db.add_compound(
            name=name.strip(),
            status=status.strip() or "active",
            mw=mw_val,
            smiles=smiles.strip() or None,
            notes=notes.strip() or None,
        )
        db.audit("compound_add", user["username"], user["role"], name.strip())
        flash(request, "Compound saved.", "success")
    except Exception as e:
        flash(request, f"Could not save compound: {e}", "error")
    return redirect("/compounds")


@app.post("/compounds/pubchem")
async def compounds_pubchem(request: Request, pc_name: str = Form(...)):
    if (r := require_user(request)):
        return r
    try:
        result = pubchem_lookup(pc_name.strip())
        request.session["pubchem_result"] = result
        request.session["compound_draft"] = {
            "name": result.get("name") or pc_name.strip(),
            "smiles": result.get("smiles") or "",
            "mw": result.get("mw") if result.get("mw") is not None else "",
            "formula": result.get("formula") or "",
        }
        src = result.get("source") or "lookup"
        flash(request, f"Found SMILES for {result['name']} ({src}).", "success")
    except Exception as e:
        flash(request, str(e), "error")
    return redirect("/compounds")


@app.post("/compounds/{compound_id}/delete")
async def compounds_delete(request: Request, compound_id: int):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/compounds")
    db.delete_compound(compound_id)
    db.audit("compound_delete", user["username"], user["role"], str(compound_id))
    flash(request, "Compound deleted.", "success")
    return redirect("/compounds")


# ── Experiments / Assays ────────────────────────────────────────
@app.get("/experiments", response_class=HTMLResponse)
async def experiments_page(request: Request):
    if (r := require_user(request)):
        return r
    return render(request, 
        "experiments.html",
        ctx(
            request,
            active="experiments",
            rows=db.list_assays(),
            compounds=db.list_compounds(),
            assay_types=ASSAY_TYPE_SUGGESTIONS,
            today=str(date.today()),
        ),
    )


@app.post("/experiments/add")
async def experiments_add(
    request: Request,
    compound_id: str = Form(""),
    assay_type: str = Form("other"),
    dose: Optional[str] = Form(None),
    survival_percent: Optional[str] = Form(None),
    notes: str = Form(""),
    assay_date: str = Form(...),
    researcher: str = Form(""),
):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/experiments")
    cid = int(compound_id) if compound_id else None
    db.add_assay(
        compound_id=cid,
        assay_type=(assay_type or "other").strip(),
        dose=float(dose) if dose not in (None, "") else None,
        survival_percent=float(survival_percent) if survival_percent not in (None, "") else None,
        notes=notes.strip() or None,
        assay_date=assay_date,
        researcher=researcher.strip() or user["display_name"],
    )
    db.audit("assay_add", user["username"], user["role"], assay_type)
    flash(request, "Assay saved.", "success")
    return redirect("/experiments")


@app.post("/experiments/{assay_id}/delete")
async def experiments_delete(request: Request, assay_id: int):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/experiments")
    db.delete_assay(assay_id)
    db.audit("assay_delete", user["username"], user["role"], str(assay_id))
    flash(request, "Assay deleted.", "success")
    return redirect("/experiments")


# ── Husbandry ───────────────────────────────────────────────────
@app.get("/husbandry", response_class=HTMLResponse)
async def husbandry_page(request: Request):
    if (r := require_user(request)):
        return r
    config = db.get_lab_config()
    return render(request, 
        "husbandry.html",
        ctx(
            request,
            active="husbandry",
            rows=db.list_husbandry(),
            compounds=db.list_compounds(),
            h_label=config.get("husbandry_label") or "Organisms",
            today=str(date.today()),
        ),
    )


@app.post("/husbandry/add")
async def husbandry_add(
    request: Request,
    event_date: str = Form(...),
    organism_label: str = Form(...),
    count: int = Form(0),
    notes: str = Form(""),
    researcher: str = Form(""),
    related_compound_id: str = Form(""),
):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/husbandry")
    cid = int(related_compound_id) if related_compound_id else None
    db.add_husbandry(
        event_date=event_date,
        researcher=researcher.strip() or user["display_name"],
        organism_label=organism_label.strip(),
        count=count,
        notes=notes.strip() or None,
        related_compound_id=cid,
    )
    db.audit("husbandry_add", user["username"], user["role"], organism_label.strip())
    flash(request, "Event saved.", "success")
    return redirect("/husbandry")


@app.post("/husbandry/{event_id}/delete")
async def husbandry_delete(request: Request, event_id: int):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/husbandry")
    db.delete_husbandry(event_id)
    db.audit("husbandry_delete", user["username"], user["role"], str(event_id))
    flash(request, "Event deleted.", "success")
    return redirect("/husbandry")


# ── Protocols ───────────────────────────────────────────────────
@app.get("/protocols", response_class=HTMLResponse)
async def protocols_page(request: Request):
    if (r := require_user(request)):
        return r
    return render(request, 
        "protocols.html", ctx(request, active="protocols", rows=db.list_protocols())
    )


@app.post("/protocols/add")
async def protocols_add(
    request: Request,
    title: str = Form(...),
    category: str = Form("general"),
    content: str = Form(""),
):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/protocols")
    db.add_protocol(
        title=title.strip(),
        category=category.strip() or "general",
        content=content,
        author=user["display_name"],
    )
    db.audit("protocol_add", user["username"], user["role"], title.strip())
    flash(request, "Protocol saved.", "success")
    return redirect("/protocols")


@app.post("/protocols/{protocol_id}/delete")
async def protocols_delete(request: Request, protocol_id: int):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/protocols")
    db.delete_protocol(protocol_id)
    db.audit("protocol_delete", user["username"], user["role"], str(protocol_id))
    flash(request, "Protocol deleted.", "success")
    return redirect("/protocols")


# ── Proteins ────────────────────────────────────────────────────
@app.get("/proteins", response_class=HTMLResponse)
async def proteins_page(request: Request, q: str = "", view: Optional[int] = None):
    if (r := require_user(request)):
        return r
    hits = []
    if q.strip():
        try:
            hits = uniprot_search(q.strip(), size=12)
        except Exception as e:
            flash(request, f"UniProt search failed: {e}", "error")
    viewing = db.get_protein(view) if view else None
    structure_text = None
    structure_fmt = "pdb"
    if viewing and viewing.get("local_path"):
        try:
            path = safe_structure_read(viewing["local_path"])
            if path.exists():
                structure_text = path.read_text(errors="replace")
                structure_fmt = "cif" if path.suffix.lower() in (".cif", ".mmcif") else "pdb"
        except ValueError:
            flash(request, "Stored structure path is invalid.", "error")
    return render(request, 
        "proteins.html",
        ctx(
            request,
            active="proteins",
            rows=db.list_proteins(),
            query=q,
            uniprot_hits=hits,
            viewing=viewing,
            structure_text=structure_text,
            structure_fmt=structure_fmt,
        ),
    )


@app.post("/proteins/rcsb")
async def proteins_rcsb(request: Request, pdb_id: str = Form(...)):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/proteins")
    try:
        meta = fetch_rcsb_entry_meta(pdb_id)
        url, content = fetch_rcsb_structure(pdb_id, "pdb")
        dest = safe_upload_path(STRUCTURES_DIR, f"{pdb_id.strip().upper()}.pdb")
        save_bytes(dest, content)
        pid = db.add_protein(
            accession=pdb_id.strip().upper(),
            name=meta.get("title") or f"PDB {pdb_id.upper()}",
            organism=None,
            source="RCSB",
            local_path=str(dest.relative_to(ROOT)),
            sequence=None,
            notes=f"method={meta.get('method')}; url={url}",
        )
        db.audit("protein_rcsb", user["username"], user["role"], pdb_id.upper())
        flash(request, f"Saved structure {pdb_id.upper()}.", "success")
        return redirect(f"/proteins?view={pid}")
    except Exception as e:
        flash(request, str(e), "error")
        return redirect("/proteins")


@app.post("/proteins/uniprot")
async def proteins_uniprot(request: Request, accession: str = Form(...)):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/proteins")
    try:
        data = uniprot_fetch(accession)
        pid = db.add_protein(
            accession=data["accession"],
            name=data["name"],
            organism=data.get("organism"),
            source="UniProt",
            local_path=None,
            sequence=data.get("sequence"),
            notes=f"length={data.get('length')}",
        )
        db.audit("protein_uniprot", user["username"], user["role"], data["accession"])
        flash(request, f"Saved UniProt {data['accession']}.", "success")
        return redirect(f"/proteins?view={pid}")
    except Exception as e:
        flash(request, str(e), "error")
        return redirect("/proteins")


@app.post("/proteins/{protein_id}/delete")
async def proteins_delete(request: Request, protein_id: int):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "write"):
        flash(request, "Read-only role.", "error")
        return redirect("/proteins")
    db.delete_protein(protein_id)
    db.audit("protein_delete", user["username"], user["role"], str(protein_id))
    flash(request, "Protein deleted.", "success")
    return redirect("/proteins")


# ── Bioinformatics ──────────────────────────────────────────────
@app.get("/bioinformatics", response_class=HTMLResponse)
async def bio_page(request: Request):
    if (r := require_user(request)):
        return r
    return render(request, 
        "bioinformatics.html",
        ctx(
            request,
            active="bioinformatics",
            fasta_results=request.session.pop("fasta_results", None),
            smiles_result=request.session.pop("smiles_result", None),
            cif_error=request.session.pop("cif_error", None),
        ),
    )


@app.post("/bioinformatics/fasta")
async def bio_fasta(
    request: Request,
    query: str = Form(...),
    fasta: UploadFile = File(...),
):
    if (r := require_user(request)):
        return r
    raw = await fasta.read()
    if len(raw) > 512_000:
        flash(request, "FASTA too large (max 512 KB).", "error")
        return redirect("/bioinformatics")
    text = raw.decode("utf-8", errors="replace")
    records = parse_fasta(text)
    results = local_search(query, records)
    request.session["fasta_results"] = results[:50]
    flash(request, f"Searched {len(records)} sequences — {len(results)} hits.", "success")
    return redirect("/bioinformatics")


@app.post("/bioinformatics/cif2pdb")
async def bio_cif2pdb(request: Request, cif: UploadFile = File(...)):
    if (r := require_user(request)):
        return r
    raw = await cif.read()
    try:
        pdb_text = cif_to_pdb(raw.decode("utf-8", errors="replace"))
        raw_name = Path(cif.filename or "structure.cif").name
        stem = raw_name.rsplit(".", 1)[0] if raw_name else "structure"
        stem = "".join(c if c.isalnum() or c in "._-+" else "_" for c in stem) or "structure"
        name = stem + ".pdb"
        return Response(
            content=pdb_text,
            media_type="chemical/x-pdb",
            headers={"Content-Disposition": f'attachment; filename="{name}"'},
        )
    except Exception as e:
        request.session["cif_error"] = str(e)
        flash(request, f"CIF→PDB failed: {e}", "error")
        return redirect("/bioinformatics")


@app.post("/bioinformatics/pubchem")
async def bio_pubchem(request: Request, name: str = Form(...)):
    if (r := require_user(request)):
        return r
    try:
        result = pubchem_lookup(name.strip())
        request.session["smiles_result"] = result
        flash(request, "PubChem lookup OK.", "success")
    except Exception as e:
        flash(request, str(e), "error")
    return redirect("/bioinformatics")


# ── Analytics ───────────────────────────────────────────────────
@app.get("/analytics", response_class=HTMLResponse)
async def analytics_page(request: Request):
    if (r := require_user(request)):
        return r
    assays = db.list_assays()
    compounds = db.list_compounds()
    samples = db.list_samples()
    return render(request, 
        "analytics.html",
        ctx(
            request,
            active="analytics",
            assays=assays,
            compounds=compounds,
            samples=samples,
            assays_json=json.dumps(assays),
            compounds_json=json.dumps(compounds),
            samples_json=json.dumps(samples),
        ),
    )


@app.get("/analytics/export.csv")
async def analytics_csv(request: Request):
    if (r := require_user(request)):
        return r
    assays = db.list_assays()
    buf = io.StringIO()
    if assays:
        writer = csv.DictWriter(buf, fieldnames=list(assays[0].keys()))
        writer.writeheader()
        writer.writerows(assays)
    else:
        buf.write("id,assay_type,assay_date,survival_percent\n")
    data = buf.getvalue().encode("utf-8")
    return Response(
        content=data,
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="assays_export.csv"'},
    )


@app.get("/analytics/plot_assays.R")
async def analytics_r(request: Request):
    if (r := require_user(request)):
        return r
    return Response(
        content=R_TEMPLATE.encode("utf-8"),
        media_type="text/plain",
        headers={"Content-Disposition": 'attachment; filename="plot_assays.R"'},
    )


# ── Users / Audit / Settings / Integrations ─────────────────────
@app.get("/users", response_class=HTMLResponse)
async def users_page(request: Request):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    return render(request, 
        "users.html", ctx(request, active="users", rows=db.list_users())
    )


@app.post("/users/add")
async def users_add(
    request: Request,
    username: str = Form(...),
    password: str = Form(...),
    role: str = Form("researcher"),
    display_name: str = Form(""),
):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    if role not in ("admin", "researcher", "viewer"):
        role = "researcher"
    try:
        db.create_user(
            username.strip(),
            hash_password(password),
            role,
            display_name.strip() or username.strip(),
        )
        db.audit("user_add", user["username"], user["role"], username.strip())
        flash(request, "User created.", "success")
    except Exception as e:
        flash(request, f"Could not create user: {e}", "error")
    return redirect("/users")


@app.post("/users/{user_id}/toggle")
async def users_toggle(request: Request, user_id: int):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    rows = {u["id"]: u for u in db.list_users()}
    target = rows.get(user_id)
    if target:
        db.update_user(user_id, active=0 if target["active"] else 1)
        db.audit("user_toggle", user["username"], user["role"], str(user_id))
    return redirect("/users")


@app.post("/users/{user_id}/delete")
async def users_delete(request: Request, user_id: int):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    if user_id == user["id"]:
        flash(request, "Cannot delete yourself.", "error")
        return redirect("/users")
    db.delete_user(user_id)
    db.audit("user_delete", user["username"], user["role"], str(user_id))
    flash(request, "User deleted.", "success")
    return redirect("/users")


@app.get("/audit", response_class=HTMLResponse)
async def audit_page(request: Request):
    if (r := require_user(request)):
        return r
    return render(request, 
        "audit.html", ctx(request, active="audit", rows=db.recent_audit(100))
    )


@app.get("/settings", response_class=HTMLResponse)
async def settings_page(request: Request):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    return render(
        request,
        "settings.html",
        ctx(request, active="settings", labs=list_labs()),
    )


@app.post("/settings/lab")
async def settings_lab(
    request: Request,
    lab_name: str = Form(...),
    lab_code: str = Form(...),
    lab_type: str = Form("General"),
    husbandry_label: str = Form("Organisms"),
    primary_color: str = Form("#2563eb"),
    accent_color: str = Form("#0d9488"),
    timezone: str = Form("America/Los_Angeles"),
):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    config = db.get_lab_config()
    # Lab code identifies the DB folder — do not rename the folder from Settings.
    # Keep stored code stable; only update display fields.
    code = (config.get("lab_code") if config else lab_code).strip().upper()
    db.save_lab_config(
        lab_name=lab_name.strip(),
        lab_code=code,
        primary_color=primary_color,
        accent_color=accent_color,
        timezone=timezone.strip() or "UTC",
        logo_path=config.get("logo_path") if config else None,
        modules=config.get("modules") if config else DEFAULT_MODULES,
        lab_type=lab_type.strip() or "General",
        husbandry_label=husbandry_label.strip() or "Organisms",
    )
    try:
        from labs import update_lab_display_name
        update_lab_display_name(code, lab_name.strip())
    except Exception:
        pass
    db.audit("settings_lab", user["username"], user["role"], lab_name.strip())
    flash(request, "Lab settings saved.", "success")
    return redirect("/settings")


@app.post("/settings/modules")
async def settings_modules(request: Request):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    form = await request.form()
    selected = form.getlist("modules")
    mods = {k: (k in selected) for k in DEFAULT_MODULES}
    db.update_modules(mods)
    db.audit("settings_modules", user["username"], user["role"], json.dumps(mods))
    flash(request, "Modules updated.", "success")
    return redirect("/settings")


@app.get("/integrations", response_class=HTMLResponse)
async def integrations_page(request: Request):
    if (r := require_user(request)):
        return r
    return render(request, 
        "integrations.html", ctx(request, active="integrations")
    )


@app.get("/guide", response_class=HTMLResponse)
async def guide_page(request: Request):
    if (r := require_user(request)):
        return r
    return render(request, "guide.html", ctx(request, active="guide"))


@app.post("/settings/labs/create")
async def settings_labs_create(
    request: Request,
    new_lab_code: str = Form(...),
    new_lab_name: str = Form(...),
):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    try:
        create_empty_lab(new_lab_code, new_lab_name.strip())
        db.audit(
            "lab_create",
            user["username"],
            user["role"],
            f"{new_lab_code.strip().upper()}:{new_lab_name.strip()}",
        )
        flash(
            request,
            f"Created empty lab {new_lab_code.strip().upper()}. Switch to it, then complete /setup.",
            "success",
        )
    except Exception as e:
        flash(request, str(e), "error")
    return redirect("/settings")


@app.post("/settings/labs/switch")
async def settings_labs_switch(request: Request, lab_code: str = Form(...)):
    if (r := require_user(request)):
        return r
    user = current_user(request)
    if not role_can(user["role"], "admin"):
        flash(request, "Admin only.", "error")
        return redirect("/")
    try:
        switch_active_lab(lab_code)
        # Prevent cross-lab session leakage
        request.session.clear()
        flash(request, f"Switched to lab {lab_code.strip().upper()}. Please sign in.", "success")
        return redirect("/login")
    except Exception as e:
        flash(request, str(e), "error")
        return redirect("/settings")


@app.get("/health")
async def health():
    return {
        "ok": True,
        "app": "custom-lab-lims-web",
        "streamlit": False,
        "active_lab": active_lab_code(),
    }
